[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="War Helios Cond Font"
FontSize="12"

KeyboardSize="1.0"
RoundCorners="15"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

#################### Background ####################

BackgroundPlaceholder="nightcity.png"
Background="example_background.png"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

DateTextColor="#D8E2EA"
TimeTextColor="#D8E2EA"

FormBackgroundColor="#0B0E1D"
BackgroundColor="#0B0E1D"
DimBackgroundColor="#0B0E1D"

LoginFieldBackgroundColor="#0B0E1D"
PasswordFieldBackgroundColor="#0B0E1D"
LoginFieldTextColor="#D8E2EA"
PasswordFieldTextColor="#D8E2EA"
UserIconColor="#a6a7ac"
PasswordIconColor="#a6a7ac"

PlaceholderTextColor="#a6a7ac"
WarningColor="#e89b0b"

LoginButtonTextColor="#D8E2EA"
LoginButtonBackgroundColor="#323648"
SystemButtonsIconsColor="#a6a7ac"
SessionButtonTextColor="#a6a7ac"
VirtualKeyboardButtonTextColor="#a6a7ac"

DropdownTextColor="#D8E2EA"
DropdownSelectedBackgroundColor="#0B0E1D"
DropdownBackgroundColor="#1D202F"

HighlightTextColor="#000055"
HighlightBackgroundColor="#b4d8ff"
HighlightBorderColor="transparent"

HoverUserIconColor="#fcfcff"
HoverPasswordIconColor="#fcfcff"
HoverSystemButtonsIconsColor="#fcfcff"
HoverSessionButtonTextColor="#fcfcff"
HoverVirtualKeyboardButtonTextColor="#fcfcff"

#################### Form ####################

PartialBlur="false"
FullBlur=""
BlurMax="48.0"
Blur="1.0"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin="Войти!"
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
